import { readFileSync } from 'node:fs';
import { expect, test } from '@playwright/test';
import { resetBoard } from './helpers.js';

// width, height and colour type from a PNG's header chunk
function pngInfo(buffer) {
  const signature = buffer.subarray(0, 8).toString('hex');
  return {
    isPng: signature === '89504e470d0a1a0a',
    width: buffer.readUInt32BE(16),
    height: buffer.readUInt32BE(20),
    colorType: buffer[25], // 2 = RGB (opaque), 6 = RGBA
  };
}

test('the page declares its icons, and every one is served', async ({ page, request }) => {
  await resetBoard(page);
  const hrefs = await page
    .locator('head link[rel~="icon"], head link[rel="apple-touch-icon"], head link[rel="manifest"]')
    .evaluateAll((links) => links.map((l) => l.getAttribute('href')));
  expect(hrefs).toEqual(
    expect.arrayContaining(['/favicon.svg', '/favicon.ico', '/apple-touch-icon.png', '/site.webmanifest']),
  );
  for (const href of hrefs) {
    const response = await request.get(href);
    expect(response.status(), href).toBe(200);
  }
  await expect(page.locator('head meta[name="theme-color"]')).toHaveAttribute('content', '#1a1714');
});

test('favicon.ico holds 16, 32 and 48px images', async ({ request }) => {
  const ico = Buffer.from(await (await request.get('/favicon.ico')).body());
  expect(ico.readUInt16LE(0)).toBe(0); // reserved
  expect(ico.readUInt16LE(2)).toBe(1); // type: icon
  const count = ico.readUInt16LE(4);
  expect(count).toBe(3);

  const sizes = [];
  for (let i = 0; i < count; i++) {
    const entry = 6 + i * 16;
    const length = ico.readUInt32LE(entry + 8);
    const offset = ico.readUInt32LE(entry + 12);
    const png = pngInfo(ico.subarray(offset, offset + length));
    expect(png.isPng).toBe(true);
    expect(png.width).toBe(ico.readUInt8(entry)); // the directory agrees with the image
    expect(png.height).toBe(png.width);
    sizes.push(png.width);
  }
  expect(sizes).toEqual([16, 32, 48]);
});

test('the home-screen icons are opaque squares of the sizes advertised', async ({ request }) => {
  const manifest = await (await request.get('/site.webmanifest')).json();
  expect(manifest.name).toBe('Inkstone');
  expect(manifest.theme_color).toBe('#1a1714');

  const files = [
    ['/apple-touch-icon.png', 180],
    ...manifest.icons.map((icon) => [icon.src, Number.parseInt(icon.sizes, 10)]),
  ];
  expect(files.map(([, size]) => size)).toEqual(expect.arrayContaining([180, 192, 512]));
  for (const [src, size] of files) {
    const info = pngInfo(Buffer.from(await (await request.get(src)).body()));
    expect(info.isPng, src).toBe(true);
    expect([info.width, info.height], src).toEqual([size, size]);
    expect(info.colorType, `${src} must have no transparency (iOS/Android mask it)`).toBe(2);
  }
});

test('the corner logo is the mark from design/logo, and it loads', async ({ page }) => {
  await resetBoard(page);
  const brand = page.locator('#brand-icon');
  await expect(brand).toHaveAttribute('src', '/logo.svg');
  expect(await brand.evaluate((img) => img.complete && img.naturalWidth > 0)).toBe(true);
});

// public/ holds copies generated by `npm run build:icons`; fail if someone edits
// the design source and forgets to regenerate (or edits the copy by hand).
test('the icons in public/ match their sources in design/logo/', () => {
  for (const file of ['logo.svg', 'favicon.svg']) {
    expect(readFileSync(`public/${file}`, 'utf8'), file).toBe(readFileSync(`design/logo/${file}`, 'utf8'));
  }
});
